// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PushTestPayload push test payload
//
// swagger:model pushTestPayload
type PushTestPayload struct {

	// data
	Data map[string]string `json:"data,omitempty"`

	// Push notification content
	Message *string `json:"message,omitempty"`

	// Push notification title
	Title *string `json:"title,omitempty"`
}

// Validate validates this push test payload
func (m *PushTestPayload) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this push test payload based on context it is used
func (m *PushTestPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PushTestPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PushTestPayload) UnmarshalBinary(b []byte) error {
	var res PushTestPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
